[Story] Move upload buttons from "Create" button context menu to "Upload" button context menu
linagora/twake-drive-legacy pull request #281
Opened 2023-11-27 16:31 UTC by tibormichel1

## Description

Upload file and upload folder options in modal menu are not shown if is clicked on upload button. If clicked on upload button, only upload folder and upload file options in context menu are shown

## Related Issue

 https://github.com/linagora/twake-drive/issues/226

## Motivation and Context
Upload button before was only able to upload files, now it makes more sense because user can select also folders to upload after clicking on upload button (no need to click create button = more intuitive approach).

## How Has This Been Tested?

Tested by myself (manual testing), checked ui as well as functionality.

## Screenshots (if appropriate):
![image](https://github.com/linagora/twake-drive/assets/144029067/53baf7b4-1096-4ee5-822b-8a932578a7f1)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added the Signed-off-by statement at the end of my commit message.

2023-11-29 12:19 UTC, MontaGhanmy commented
Hi @tibormichel1, thank you for your interest in Twake-drive. I just left you some feedback to fix before merging your PR. please let me know if anything is not clear.

2023-11-29 12:20 UTC, MontaGhanmy requested changes

2023-11-29 12:20 UTC, MontaGhanmy commented on tdrive/frontend/src/app/views/client/body/drive/modals/create/index.tsx
Please duplicate the 'create' modal into a dedicated 'upload' modal or, ideally, create a generic 'modal' component and extend both 'create' and 'upload' from it. The current structure of combining both functionalities within a single modal complicates code comprehension and maintenance.

2023-11-29 12:20 UTC, MontaGhanmy commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
Please make sure the modal closes once the file/folder is uploaded.

2023-12-05 10:42 UTC, MontaGhanmy reviewed
@tibormichel The only remaining issue is with closing the modal once the upload is finished.

2024-04-02 08:02 UTC, shepilov approved these changes

2024-04-02 08:04 UTC, merged

2024-04-02 08:14 UTC, ericlinagora reviewed
The CreateModalOption duplication is a bit odd and has an odd name for a component but not really an issue