Webdav express
linagora/twake-drive-legacy pull request #643
Opened 2024-08-27 14:15 UTC by rumata-feathers

WebDAV implementation

## Description
This is implementation the WebDAV protocol for our application using the nephele library.
Key components of this implementation include:
- Creating new 'webdav' service
- Custom adapter class to interface
- Resource class wrapper for drive items
- Device authorisation
- Implementing locks for the drive items

## Related Issue
https://github.com/linagora/twake-drive/issues/573

## Motivation and Context
WebDAV protocol is needed for desktop synchronisation

## How Has This Been Tested?
1. Manual testing using curl requests to simulate various WebDAV operations
2. Practical testing by mounting the WebDAV server as a network drive:
   - Tested on macOS Sonoma
   - Tested file creation, deletion, and modification through the mounted drive
  
Testing environment:
  - Native explorer
  - ACCOUNTS_TYPE=internal

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added the Signed-off-by statement at the end of my commit message.

2024-08-27 15:04 UTC, chibenwa commented on tdrive/backend/node/src/services/documents/entities/drive-file-lock.ts
> +export class DriveLock {
Sorry to be curious but could you explain me what a "lock" is in this context? What is it used for? 
Is this mandated by DAV?

2024-08-27 15:04 UTC, chibenwa commented on tdrive/backend/node/src/services/documents/entities/drive-file-lock.ts
> +  timeout: number;
A duration without unit?

2024-08-27 15:06 UTC, chibenwa commented on tdrive/backend/node/src/services/documents/entities/drive-file-lock.ts
> +  created_at: number;
I understand this is a date stored a s a unix timestamp. What is the timezone?
Also we do not have more expressive types for dates offered by the DB driver?

2024-08-27 15:07 UTC, chibenwa commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  locks: DriveLock[];
We add a column to an existing schema. We shall document the SQL command to add it in production data. Ops will <3 you for taking this care.

2024-08-27 15:09 UTC, chibenwa commented on tdrive/backend/node/src/services/user/entities/device.ts
> +  @Column("id", "uuid", { generator: "uuid" })
How do we migrate existing data?
Is changing type of a column allowed on a production system?

2024-08-27 15:11 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  locks: DriveLock[];
drive has a *special* ORM, that just adds them itself if they're missing

(yes actual migrations are a current topic)

2024-08-27 15:11 UTC, chibenwa commented on tdrive/backend/node/src/services/user/entities/device.ts
> +  password: string;
Is this random enough? For such a sensible use case I would make sure I use cryptography grade random with enough entropy.

Also: does it make sense to store a password in clear? What's the impact if it gets read?

If it is stored only for validation later shouldn't we use bcrypt and friends?

2024-08-27 15:14 UTC, chibenwa commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +  //TODO[ASH] username will be actually a device, and we will need to get real user by device
Still relevant? Remove TODO?

2024-08-27 15:15 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/entities/device.ts
> +  @Column("id", "uuid", { generator: "uuid" })
this, the *special* ORM doesn't do I think... but that table should be empty for the moment, this is the first actual use, we'll have to remember to test this before deploy

2024-08-27 15:17 UTC, chibenwa reviewed
Partial review.
Disclaimer: I do not know tdrive, I do not know dav.
Feel free to discard comments if irrelevant.
Also: no tests? I see complex logic all across the place and many way things can go bust. It would be invaluable to invest in HTTP layer tests exercising this brand new DAV extension.
(from my experience standards needs **extensive** tests)

2024-08-27 15:23 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/entities/device.ts
> +  password: string;
I think we might need a clear text to support digest authentication (if realm is configurable).

The UUID should have enough entropy for crypto https://github.com/uuidjs/uuid

2024-08-27 15:28 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file-lock.ts
> +  created_at: number;
But unix timestamps don't need timezones, they are an instant in time past after 1/1/1970 UTC. We use a custom ORM that was supposed to be compatible with postgres, cassandra and mongo, and for that purpose is super generic. Something to fix, but out of scope of this PR

2024-08-27 17:26 UTC, ericlinagora commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
Am I reading this right ? Does this disable CORS site-wide ????

2024-08-27 19:18 UTC, ericlinagora requested changes

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  locks: DriveLock[];
If DriveLocks are stored in that json field, why create the entity and db table and all that ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +   * Returns the file
I dont think this kind of documentation really adds anything ("returns the file" it's not hard to see the return type). However it would be nice, also eg on exported things like DriveLock

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +   * Copies item to destination
...

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    return Promise.resolve(driveFile);
No need for `Promise.resolve` in an async function

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    assert(item.item.parent_id != null, "Cannot copy root");
what if `id` is not found ? How do you return say a 404 ? What about the asserts, shouldn't a lot of them be 400/401 type errors ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    // TODO: keep it or "write" level-access to parent allows to change any child?
@shepilov I think this is related to inheritance of rights ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +  move = async (
Comments from `copy` apply

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    assert(content.parent_id != null && content.name != "root", "Cannot move to root");
why not ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    content: Partial<DriveFile>,
it's really not clear from the argument names what's what... The content has the new parent_id of the destination ? id is the source file ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/entities/device.ts
> +import {generators} from "openid-client";
I think this is an IDE accident

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
whats `FCM` ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/services/webdav.ts
> +export class WebDAVServiceImpl {
I dont get what this is doing ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +      let pathname = decodeURI(url.pathname);
doesn't really matter here, but in general you should always use `decodeURIComponent` not `decodeURI` (and the reciprocals). And you should really split by `/` first, then decode, in case of a filename containing `/`

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +      const pathname_arr = pathname.split("/");
at some point consider refactoring repeated code, not only does it document what's happening in the function name instead of having to read the code, but also if this logic ever needs to be tweaked/fixed, now we have to do it at many places, and sooner or later, a place will be forgotten

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +      return resource;
Is it not an error if a resource at that path already exists ? More-so if permissions don't permit a write ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +      if (method === "PROPATCH") {
`PROP*P*ATCH`

but also, why, given the rest of the function ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +  AdapterService = await eval("import('nephele').then(build_adapter)");
I think it's worth a comment to document our shame, how `eval` keeps TS from transpiling `import` which wouldn't work with whatever module type combination it was

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +  method: "undefined", // cannot retrieve method from url
Yeah but that makes this a truthy string, I let it slide for the one above because it looked like it would be painful to change the type, but here ? ditto for req-id, make up a guid or whatever, ditto for transport, if we don't know, we don't (though I guess "insecure" is a good default)...

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/drivelock.ts
> +    );
Maybe I need to look into this more, but it seems provisional can't be ignored until expired, and also that you'd need to check parent items for locks with `.depth == "infinity"`, and if this lock is infinity, all child items for any locks ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/index.ts
> +  // const routes = eval ("import('nephele').then(builder)");
needed comment ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +import { ResourceService } from "./fileResource";
our filename convention is `kebab-case`

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +    // const versions = await this.resource.getVersions();
?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +        return Promise.resolve("en");
is it an issue if we don't have a value for properties like this ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +        return Promise.resolve((this.resource.file.added || new Date().toISOString()).toString());
please remove Promise.resolve in async functions unless you need them for a good reason (not here)

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +          return Promise.resolve("PropertyNotFoundError");
nephele wants just that value returned and not an error thrown or something !?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +          (this.resource.file.last_modified || new Date().toISOString()).toString(),
@shepilov is it possible that `last_modified` is null but not `created_at` ?

If we don't have a value, we shouldn't just make up "now", this value's validity may be crucial for synchronisation software

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +        throw new Error("PropertyNotFoundError") as PropertyNotFoundError;
if nephele uses `instanceof`, which it probably does, this is going to break. The actual prototype has to be exported, from that place we do the `eval` I suppose

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +    return Promise.resolve();
At least a `//TODO`, and maybe see how clients react to refusing this

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +    return Promise.resolve();
ditto for all the non implemented functions below

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +    const properties = [
Note: We may need to store client-specific properties and retrieve them here, maybe worth a `//TODO` for the moment

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +    }
Could be worth parallelising this, eg with `Promise.all(properties.map(....`

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +            const device_password = credentials.split(":")[1];
because there's no checks that neither `device_id` nor `device_password` have no `:` chars, it's better to split it once, then check you have exactly 2 results, at the very least we'll get a helpful error out of it

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +            throw new nephele.UnauthorizedError("Error while authorising");
not sure how nephele handles this, but this error could be anything. If you know it's the wrong user/pass, then fine, send a 401, but if you don't, send a 500, because when the client gets a 401, it will delete its stored credentials since it thinks them invalid, which mean a short network error, a restarting db, stuff like that and everyone has to re-enter their logins

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +        console.log("AUTHENTICATOR::cleanAuthentication is called()");
no `console.log`s please

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +        authenticator: authenticator, // You need to define this
I get this is example copy-pasta, but them comments....

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +      console.log(request);
.

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +            fastify.log.error("Nephele error:", err);
please use our logger, `import { logger } from "./core/platform/framework/logger";` (path is from `src/`, you'll need to `../` it)

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +      fastify.use(`${webdavUrl}`, webdavMiddleware);
why not just `webdavUrl` ? Can it be a non-string ? (and if so, do we want this to work ?)

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +      reply.send({ message: "Test route" });
needed ?

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +    console.debug(fastify.printRoutes());
.

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> +export const routes = eval("import('nephele').then(builder)");
I'd really prefer if we did this horrible eval hack in a single place and exported what we need from there, and documented the raison-d'etre

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/src/utils/files.ts
> + */
Ah, great inline documentation ! Personally I prioritise this over the separate documentation, makes it less likely to rot, and it's right there in the IDE

2024-08-27 19:18 UTC, ericlinagora commented on tdrive/backend/node/tsconfig.json
> +      },
technically that's not valid json, seems benign, but also, why in this pr ?

2024-08-27 19:21 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    assert(content.parent_id != null && content.name != "root", "Cannot move to root");
Oh, because My Drive is not root..... I see.... this is awkward, maybe it should be and make company drive have another url for its root

2024-08-27 21:32 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +  AdapterService = await eval("import('nephele').then(build_adapter)");
does something like `global["im" + "port"]('nephele')` work ?

2024-08-27 21:34 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +  method: "undefined", // cannot retrieve method from url
to please the gods of typing per microsoft, maybe `undefined as string` (or `undefined as unknown as string`), is the better option

2024-08-28 09:47 UTC, shepilov commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
yes, it should be reconfigured only for the webdav uri

2024-08-28 09:49 UTC, ericlinagora commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
i'm surprised webdav clients care at all about CORS

2024-08-28 09:51 UTC, chibenwa commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
I had similar issues with JMAP

 - CORS do not makes sense for JMAP so *native* JMAP clients ignores them
 - But web based JMAP clients are bound to browser safety limitations hence CORS...

2024-08-28 09:51 UTC, shepilov commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    // TODO: keep it or "write" level-access to parent allows to change any child?
yes, and it's more complicated than "keep it or "write" level-access to parent allows to change any child"

2024-08-28 09:54 UTC, shepilov commented on tdrive/backend/node/src/services/user/entities/device.ts
> +  password: string;
@rumata-feathers, could you please take a look at how password is encoded in the "user" entity, and do the same with the same salt and the same passwordEncode component

2024-08-28 09:54 UTC, ericlinagora commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
That makes sense, but still I'd prefer if native clients indeed ignore to keep them everywhere, and if/when we do have a browser client to support, and if it is a problem, then we look into removing them for that

2024-08-28 09:56 UTC, shepilov commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
football club monaco

2024-08-28 09:56 UTC, shepilov commented on tdrive/backend/node/src/services/webdav/services/webdav.ts
> +export class WebDAVServiceImpl {
probably it should do what adapter service is doing

2024-08-28 10:01 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/services/webdav.ts
> +export class WebDAVServiceImpl {
look at the whole file, if that's useful is purely by side-effect and worth a comment

2024-08-28 10:02 UTC, shepilov commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +          (this.resource.file.last_modified || new Date().toISOString()).toString(),
I can't imaging a situation when we have `created_at` but don't have `last_modified`, but if assume that everything is possible in Twake Drive, what is true meanwhile, yes, it should be `created_at` and only then `now()`

2024-08-28 10:04 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/properties.ts
> +          (this.resource.file.last_modified || new Date().toISOString()).toString(),
I think it should never be `now()`, if we don't have a date, then tell the client we don't, inventing a date that is always changing would be far messier

2024-08-28 14:47 UTC, rumata-feathers commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
Firebase Cloud Messaging

2024-08-28 14:52 UTC, rumata-feathers commented on tdrive/backend/node/src/services/webdav/web/adapter.ts
> +      return resource;
Not exactly, because newResource function in the adapter does not create the drive item, but the empty resource. All the checks are later done in the fileResource

2024-08-30 13:41 UTC, chibenwa commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
What is FCM used for in a web application?

2024-09-02 12:51 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
I got an offline answer: so this table represents devices that have ±delegate authentication for a user, and were used for notifications. I think it's legacy though in this case and we should explicitely set it to something indicating there are no notifications for webdav "device"s, @shepilov ?

2024-09-02 12:59 UTC, shepilov commented on tdrive/backend/node/src/services/user/services/users/service.ts
> +      "FCM",
or just remove type field at all

2024-10-01 11:55 UTC, ericlinagora commented on tdrive/backend/node/src/services/webdav/web/routes.ts
> -    fastify.all("webdav/*", (request, reply) => {
apparently this chunk is vital, without it, we get 404s only in the webdav stuff....

2024-10-01 12:09 UTC, shepilov approved these changes

2024-10-01 13:32 UTC, shepilov requested changes
!

2024-10-02 13:43 UTC, ericlinagora commented on .github/workflows/build.yml
> +          docker compose -f docker-compose.tests.yml run --rm -e "NODE_OPTIONS=--unhandled-rejections=warn --experimental-vm-modules" -e SEARCH_DRIVER=mongodb -e DB_DRIVER=mongodb -e PUBSUB_TYPE=loca
Still needed after the `eval` evil hack ?

2024-10-11 14:12 UTC, shepilov commented on tdrive/backend/node/src/core/platform/services/webserver/index.ts
> +    // this.server.register(corsPlugin, this.configuration.get<FastifyCorsOptions>("cors", {}));
as far as I have seen in the WebDAV, it will be impossible to use web WebDAV client with CORS as far as they both use OPTIONS request to.
CORS support in fastify automatically answers this OPTIONS request with "Access-Control-Allow-Origin: " and hence doesn't pass further to WebDAV app.
So this support of the WebDAV for web clients will be limited to browser that a sending this "preflight" OPTIONS request and we will need to remove fastify on this path
So for now let's just  disable CORS for WebDAV URLs only

2024-10-11 14:13 UTC, shepilov commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  locks: DriveLock[];
Just naive copy-paste implementtion, anyway we will need to work more on lock

2024-10-11 14:34 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  locks: DriveLock[];
yeah, but it does make sense to have them indexed in the db: when locking, we need to query locks above and below and on same item

2024-10-13 10:47 UTC, ericlinagora commented
rclone for testing webdav:
- copy url in twake drive account settings
- `rclone config` for interactive, pick webdav, vendor = other, no user/pass (it's in the url), lets say you called the remote `td`
- `rclone lsl td:` should list My Drive
- Debug flags: `-vv` for debug level, request debugging at https://rclone.org/docs/#dump-flag-flag-flag

The config file look like:

```
$ cat ~/.config/rclone/rclone.conf 
[td]
type = webdav
url = http://f2a30b0f-ac2f-4a87-b0d5-c718b0d3b0e2:53503dce-9e7b-4f2d-9bd0-7a894386ce27@localhost:4000/internal/services/webdav/v1/webdav/My%20Drive/
vendor = other
```

2025-03-29 18:38 UTC, closed without merging