🐞 Add antivirus inside Twake Drive
linagora/twake-drive-legacy pull request #725
Opened 2024-11-04 09:43 UTC by MontaGhanmy

=

2024-11-04 12:25 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +export type Status = "uploaded" | "scanning" | "scan_failed" | "safe" | "malicious" | "skipped";
can you call this something that makes it clear it's the antivirus status on the file/enum/etc ?

2024-11-11 04:28 UTC, shepilov commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  av_status: AVStatus;
is there a default status? what status will be when the antivirus feature is disabled?

2024-11-11 04:30 UTC, shepilov commented on tdrive/backend/node/src/services/av/service/index.ts
> +    const driveItem = await repo.findOne(
you don't need to find files one more time, you've just created them

2024-11-11 04:32 UTC, shepilov commented on tdrive/backend/node/src/services/av/service/index.ts
> +      await repo.save(driveItem);
could you please move this save function back to document service, and here make only scan and return status back

2024-11-11 04:32 UTC, shepilov commented on tdrive/backend/node/src/services/av/service/index.ts
> +        `Error scanning file ${driveItem.last_version_cache.file_metadata.external_id}`,
could you make and AVException class to be monitored

2024-11-11 04:35 UTC, shepilov commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      if (globalResolver.services.av.avEnabled && version) {
you will have NPE here if antivirus is not in the services list

2024-11-11 04:36 UTC, shepilov commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +  av_status: AVStatus;
found below in the getDefaultDriveIten

2024-11-11 04:40 UTC, shepilov commented
@MontaGhanmy we will also need to add also email notification for the not-scanned and infected files

2024-11-11 12:04 UTC, MontaGhanmy commented
> @MontaGhanmy we will also need to add also email notification for the not-scanned and infected files

I just did for the following status "malicious", "skipped" and "scan_failed".

2024-11-18 13:49 UTC, shepilov commented on tdrive/frontend/src/app/views/client/body/drive/documents/document-row.tsx
> +            {item?.av_status === 'safe' && <ShieldCheckIcon className="w-5 text-teal-400" />}
Could you please remove "safe" status?

2024-11-19 10:50 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    const unsafeStatuses = ["malicious", "scanning", "scan_failed", "skipped"];
why not simply `!- "safe"` ? this would resist further status additions safely

2024-11-19 10:53 UTC, ericlinagora commented on tdrive/backend/node/src/core/platform/services/email-pusher/templates/en/notification-document-av-scan-alert.eta
> +                      Issue: ${ it.notifications[0].item.av_status === "scan_failed" ? "Scan Failed 🔍" : it.notifications[0].item.av_status === "malicious" ? "Malicious Content Detected ⚠️" : "Fichie
what are you saying here ? "if it's too fat better say it in french" ? :D

2024-11-19 10:55 UTC, ericlinagora commented on tdrive/backend/node/src/core/platform/services/email-pusher/templates/fr/notification-document-av-scan-alert.eta
> +                      Problème : ${it.notifications[0].item.av_status === "scan_failed" ? "Échec de l'analyse 🔍" : "Contenu malveillant détecté ⚠️"}
but `en` version has 3 values here. Personally I'm not sure about the e-mail for files being too big... I think for that warning at download is annoyance enough

2024-11-19 10:59 UTC, ericlinagora commented on tdrive/backend/node/src/services/av/service/index.ts
> +          this.logger.info(`Scan failed for item ${item.id} due to error: ${err.message}`);
`logger.error({err}, "Scan failed...`

2024-11-19 11:03 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +export type AVStatus = "uploaded" | "scanning" | "scan_failed" | "safe" | "malicious" | "skipped";
sometimes it can be useful to split a type, let the compiler do some additional checks. For ex.:
```
export type AVStatusSafe = "safe";
export type AVStatusUnsafe = "uploaded" | "scanning" | "scan_failed" | "malicious" | "skipped";
export type AVStatus = AVStatusSafe | AVStatusUnsafe;
```

The benefit is that if you are working with a function/var/etc that should only ever work if you know it's safe or unsafe, use the specific type and ensure it's garanteed the status before it gets to that function/var.

2024-11-19 11:05 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> + * - `"uploaded"`: The file has been uploaded but not yet scanned.
This documentation is great, but I think it's better suited on `AVStatus`: if it changes, the documentation needs to be updated, and this way, everywhere it's used will link to that.

2024-11-19 11:08 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/engine/index.ts
> +      return; // Early return on unknown event type
this should throw no ? If we get an unknown event, calling code must be buggy too and interrupted no ?

2024-11-19 11:08 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/engine/index.ts
> +      DocumentEvents.DOCUEMNT_AV_SCAN_ALERT,
`DOCUEMNT`

2024-11-19 11:12 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +              await this.handleAVStatusUpdate(driveItem, av_status, context);
Why not do this immediately ? if this callback is called, the AV is done, regardless of if the rest runs or or not. And also, I kinda hoped that stuff that reads it, like generatePreview, would by default refuse unsafe files (and if needed for some cases, have an override parameter to opt-in into ignoring av_status).

2024-11-19 11:14 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +            await this.notifyAVScanAlert(driveItem, context);
As much as I've convinced it was dumb to want to display safe status in the ui, I think this notification also is only annoying. Other drives don't do it afaik

2024-11-19 11:15 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +          this.logger.error(`Error scanning file ${driveItemVersion.file_metadata.external_id}`);
Shouldn't this re-throw ?

2024-11-19 11:17 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      throw new CrudException("Cannot update a malicious file", 403);
Why not ? At this point the file is actually uploaded anyway, we do store and and let users, after alert, download malicious files. I think this error for the client should be advisory at most, but, the operation itself, the upload, succeeded, so 200.

2024-11-19 11:35 UTC, shepilov approved these changes

2024-11-19 12:26 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> +export type AVStatus = "uploaded" | "scanning" | "scan_failed" | "safe" | "malicious" | "skipped";
If we;re keeping the array of unsafe values, it should be right next to this. Everything that needs to change at the same time should be as close as possible, specially if forgetting something wouldn't cause an error.

2024-11-19 12:46 UTC, MontaGhanmy commented on tdrive/backend/node/src/core/platform/services/email-pusher/templates/en/notification-document-av-scan-alert.eta
> +                      Issue: ${ it.notifications[0].item.av_status === "scan_failed" ? "Scan Failed 🔍" : it.notifications[0].item.av_status === "malicious" ? "Malicious Content Detected ⚠️" : "Fichie
Yes, typo I guess.

2024-11-19 12:48 UTC, MontaGhanmy commented on tdrive/backend/node/src/core/platform/services/email-pusher/templates/fr/notification-document-av-scan-alert.eta
> +                      Problème : ${it.notifications[0].item.av_status === "scan_failed" ? "Échec de l'analyse 🔍" : "Contenu malveillant détecté ⚠️"}
It's one of the requirements I discussed with Anton to have a notification for the large files as well.

2024-11-19 12:50 UTC, ericlinagora requested changes

2024-11-19 12:50 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      if (globalResolver.services.av?.avEnabled) {
if it's not enabled, then fail the endpoint as if it didn't exist no ?

2024-11-19 12:51 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +            await this.notifyAVScanAlert(item, context);
see above comment

2024-11-19 12:52 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +          );
this should re-throw

2024-11-19 12:52 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      CrudException.throwMe(error, new CrudException("Failed to create Drive item version", 500));
wrong message

2024-11-19 12:53 UTC, MontaGhanmy commented on tdrive/backend/node/src/services/documents/services/engine/index.ts
> +      return; // Early return on unknown event type
The email notification is called through the event bus, so the calling code won't be interrupted either ways. Probably I can improve the error message here to indicate it belongs the notification dispatcher.

2024-11-19 12:54 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +    if (["malicious", "scan_failed"].includes(status)) {
All these enum lists should be exported from the same place, eg AVStatusesToNotifyUserOF =...

2024-11-19 12:55 UTC, MontaGhanmy commented on tdrive/backend/node/src/services/documents/entities/drive-file.ts
> + * - `"uploaded"`: The file has been uploaded but not yet scanned.
The documentation here makes part of the DriveFile documentation. I think it's great idea to gave it right next to the AVStatus type but that would mean leaving the DriveFile documentation without that field or having to duplicate it.

2024-11-19 12:57 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/utils.ts
> +  if (gr.services.av?.avEnabled && item.av_status !== "safe") {
I don't think this is what we discussed. Skipped files should be included. queued, failed or malicious files also if the user was warned.

2024-11-19 12:59 UTC, ericlinagora commented on tdrive/backend/node/src/services/files/services/index.ts
> +    if (entity.upload_data.size < this.max_preview_file_size) {
shouldn't this as a failsafe also check av status ?

2024-11-19 13:00 UTC, ericlinagora commented on tdrive/backend/node/src/services/user/web/types.ts
> +  COMPANY_AV_ENABLED = "company:av_enabled",
why the `enabled` ? aren't they all wether or not the feature is enabled ?

2024-11-19 13:01 UTC, ericlinagora commented on tdrive/backend/node/test/e2e/documents/documents-pagination-sorting.spec.ts
> +      await new Promise(resolve => setTimeout(resolve, 3000));
O.o what is this waiting for ?

2024-11-19 13:01 UTC, ericlinagora commented on tdrive/backend/node/test/e2e/documents/documents-search.spec.ts
> +    console.log("🚀🚀 documents", documents.entities);
debug ?

2024-11-19 13:03 UTC, ericlinagora commented on tdrive/docker-compose.dev.mongo.yml
> +      - tdrive_network
I think this is unused code, it's not in anyone's dependency (doesn't includee healthcheck)

2024-11-19 13:15 UTC, MontaGhanmy commented on tdrive/docker-compose.dev.mongo.yml
> +      - tdrive_network
This is needed to run a clamav service locally when testing with this mongo compose file. I use it all the time.

2024-11-19 13:22 UTC, ericlinagora commented on tdrive/docker-compose.tests.yml
> +      - 3310:3310
would be nice to have a real health check:

```yaml
    healthcheck:
      test: ["CMD-SHELL", "echo 'PING' | nc -w 5 localhost 3310"]
      interval: 30s
      timeout: 10s
      retries: 5
```

2024-11-19 13:23 UTC, MontaGhanmy commented on tdrive/backend/node/src/services/user/web/types.ts
> +  COMPANY_AV_ENABLED = "company:av_enabled",
What do you suggest then? It's a name and should be indicative of what it does, AV alone doesn't mean much for someone who's not familiar with the code.

2024-11-19 13:24 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +  reScan = async (id: string, context: DriveExecutionContext): Promise<DriveFile> => {
just fyi, `rescan` is a single word

2024-11-19 13:38 UTC, ericlinagora commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      this.logger.error({ error: `${error}` }, "Failed to check malicious files");
don't make error a string here, give pino the full error object

2024-11-19 14:07 UTC, shepilov commented on tdrive/backend/node/src/services/documents/services/index.ts
> +      throw new CrudException("Cannot update a malicious file", 403);
Sorry, we forbid ANY kind of action with a files except deleting and downloading

2024-11-19 16:39 UTC, merged