Add testing identifier to elements
linagora/twake-drive-legacy pull request #764
Opened 2024-12-09 14:16 UTC by lethemanh

Add testing identifier to elements

## How Has This Been Tested?
The test id class names have prefix `testid:`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added the Signed-off-by statement at the end of my commit message.

2024-12-10 15:51 UTC, ericlinagora requested changes

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/atoms/button/button.tsx
> +        `testid:${props.testClassId}`
please don't add a class for undefined, it's just clutter in the html. (this happens bellow also, but I'll only comment here).

maybe it's worth making a helper function that takes the id and returns `id ? ' testid:' + id : ''` (note the space) and call that from where it's injected into class names, this way, say we decide to change the "testid:" prefix, it would be easier, and everywhere will be protected from applying the testid:undefined class.

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/atoms/input/input-checkbox-slider.tsx
> +      data-checkbox-id={props.testClassId}
what's the purpose of this attribute ? (also only commenting once, but happens again eg: `data-input-id` )

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/components/menus/menu.jsx
> +        {},
if you need to fill a value for an optional param, consider just using `undefined`, this instead creates a new object and could have a different meaning to that function than an undefined one

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/components/menus/menus-body-layer.jsx
> +                    testClassId={item.dataMenuId}
the mix of class, classid, id, data etc is a bit confusing.

In this example, the class id could just be menu-item, and because in this case we want both the list and to distinguish them, add the data-menu-id attribute also. Also there's no guarantee item.dataMenuId is globally unique on its own.

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +        <DocumentRow {...commonProps} testClassId="browser-document-row" />
this is great, semantically what i would have done also. But please check because using css selectors makes it easy to find by hierarchy, if there is something else in browser to select, then maybe the browser part should be on it and only document-row here. We can then select just as easily `.browser .document-row` and if there's other stuff in the browser, we can reuse that parent class

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +                              {},
default to undefined please (ok this too repeats below so I'll stop this comment on this one)

2024-12-10 15:51 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/modals/create/index.tsx
> +                      testClassId={app.emptyFile.name}
I really hate dynamic values in the test class, they should only serve to pick a ui element. If many match and the difference is only data, and if we can't use the text inside (eg: for files we can, but for menu items we can't because they're translated, filenames aren't), then I think we should add separate the dynamic data into data-* attributes.

Now this specific case is annoying:
  - The default filename should probably be translated (Untilted.docx should probably be mới.docx - well, approx :) )
  - Today the actual filename is kind of used as an ID to differentiate docx from xlsx etc, so, this is correct code now

2024-12-10 15:52 UTC, ericlinagora commented
Note - at this timestamp just closed the review because the code was updated while it was pending, so I'll restart instead of continuing on the old version

2024-12-10 16:40 UTC, ericlinagora requested changes
overall this is a ton of work well done, my issue is that it was too early/quickly done, and i see testids more as a last resort, only better than using labels/roles or data-test-id. If there's any other reliable way to identify something we should probably do that. I think after the mini fixes we'll take it in, then do a second pass review with QA with actual script test cases etc.

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/components/file-uploads/pending-file-components/pending-file-row.tsx
> +      <div className="file-progress-bar-container testid:pending-file-progress-bar">
this is one example where i think the existing classname was largely sufficient to select this

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/components/menus/menus-manager.jsx
> +  async openMenu(menu, domRect, positionType, options, dataMenuId) {
if dataMenuId is the testClassId , to avoid confusion, call it the same please

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/components/search-popup/parts/result-context.tsx
> +    <div className="flex overflow-hidden whitespace-nowrap text-ellipsis testid:result-context">
result context is super vague, please, search result context (if we interact with it in the tests at all, or container, or plural results, i'm not sure how context applies to this component name tbh)

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +                    <Button theme="secondary" className="ml-4 flex flex-row items-center" testClassId="browser-button-context">
say you're reading a test, it goes page.locator('.testClassId:browser-button-context'); and you didn't know you added this, it's pretty unclear right ?

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/context-menu.tsx
>                icon: 'share-alt',
if it's an id exclusively used for tests, please make it clear, but also this is one case where we can actually distinguish items the way the user would, by using the icon (name) ?

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/modals/confirm-trash/index.tsx
> +    <Modal className="confirm-trash-modal" open={state.open} onClose={() => setState({ ...state, open: false })}>
`testid:`

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/common/account.tsx
> +          id: 'username',
ditto, if this is a testId, call it as such, `id` has a pretty unique meaning

2024-12-10 16:40 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/common/disk-usage.tsx
> +              <div style={{ width: (100 - used) +  '%' }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-grey-500 testid:disk-usage-100"></div>
i think technically this one is showing the free space

2024-12-10 16:42 UTC, ericlinagora commented on tdrive/frontend/src/app/components/menus/menus-manager.jsx
> +  async openMenu(menu, domRect, positionType, options, dataMenuId) {
(but if it should become `data-menu-id=""` then great)

2024-12-11 02:19 UTC, lethemanh commented on tdrive/frontend/src/app/atoms/input/input-checkbox-slider.tsx
> +      data-checkbox-id={props.testClassId}
I've remove it

2024-12-11 02:33 UTC, lethemanh commented on tdrive/frontend/src/app/atoms/button/button.tsx
> +        `testid:${props.testClassId}`
It's been resolved

2024-12-11 02:43 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +        <DocumentRow {...commonProps} testClassId="browser-document-row" />
I understand your idea, but this name has a rule behind, it helps to reduce the number of parent classes needed for selector

2024-12-11 02:56 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/body/drive/modals/create/index.tsx
> +                      testClassId={app.emptyFile.name}
Actually, QA want each app in this modal has an unique test id so I have to use its name, but also I checked that `app.emptyFile.name` is key for translation so I think it can be use as test id in this case.
![CleanShot 2024-12-11 at 09 55 46@2x](https://github.com/user-attachments/assets/68608595-d93b-44f4-8bdd-0592a95d4f51)

2024-12-11 03:00 UTC, lethemanh commented on tdrive/frontend/src/app/components/file-uploads/pending-file-components/pending-file-row.tsx
> +      <div className="file-progress-bar-container testid:pending-file-progress-bar">
As I mentioned in this [comment](https://github.com/linagora/twake-drive/pull/764#discussion_r1879243652)

2024-12-11 03:01 UTC, lethemanh commented on tdrive/frontend/src/app/components/menus/menus-manager.jsx
> +  async openMenu(menu, domRect, positionType, options, dataMenuId) {
It's been renamed

2024-12-11 04:06 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/common/account.tsx
> +          id: 'username',
It's been renamed

2024-12-11 04:07 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/common/disk-usage.tsx
> +              <div style={{ width: (100 - used) +  '%' }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-grey-500 testid:disk-usage-100"></div>
It's been renamed

2024-12-11 04:07 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/body/drive/modals/confirm-trash/index.tsx
> +    <Modal className="confirm-trash-modal" open={state.open} onClose={() => setState({ ...state, open: false })}>
Updated

2024-12-11 04:07 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/body/drive/context-menu.tsx
>                icon: 'share-alt',
I've changed into `testClassId`

2024-12-11 04:07 UTC, lethemanh commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +                    <Button theme="secondary" className="ml-4 flex flex-row items-center" testClassId="browser-button-context">
It's been renamed

2024-12-11 04:08 UTC, lethemanh commented on tdrive/frontend/src/app/components/search-popup/parts/result-context.tsx
> +    <div className="flex overflow-hidden whitespace-nowrap text-ellipsis testid:result-context">
It's been renamed

2024-12-11 12:04 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/modals/create/index.tsx
> +                      testClassId={app.emptyFile.name}
> Today the actual filename is kind of used as an ID to differentiate docx from xlsx etc, so, this is correct code now

Like i wrote, this one is annoying, and we'll probably have to change it in the future, but now, this is as good as possible

2024-12-11 12:09 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +        <DocumentRow {...commonProps} testClassId="browser-document-row" />
But we don't want to reduce the number of parent selectors, and this means:

1) we have to repeat multiple times the parent's name
2) it's not composable if this is reused in multiple places
3) it the parent is repeated then using the hierarchy ensures we get the consistent set of children
4) if we don't need the parent in the selector because this isn't reused, repeated, etc ; then there's still no reason to repeat the parent selector on each child

please don't mix parent and child element, the DOM will let us choose how much hierarchy we want to specify and change it easily without changing the code if we need to

2024-12-11 12:21 UTC, ericlinagora commented on tdrive/frontend/src/app/components/file-uploads/pending-file-components/pending-file-row.tsx
> +      <div className="file-progress-bar-container testid:pending-file-progress-bar">
yes but we should see the test id as a last resort, when we can't use selectors that would already exist. This is mostly for anything that doesn't have an id and has only tailwind style classes. But in this case, it was just as easy to write the test without adding this. That's why I wanted to add the test ids only at the request of QA by necessity.

2024-12-11 12:30 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +        <DocumentRow {...commonProps} testClassId="browser-document-row" />
Here is one example to clarify why this is a very bad idea, beyond just having to repeat code, not using the browser dichotomic search, being uncomposable, breaching concern separation etc. Imagine we want to read each person in the list:

```html
<li id="person">
  <div id="name">name 1</div>
  <div id="phone">123</div>
</li>
<li id="person">
  <div id="name">name 1</div>
  <div id="phone">123</div>
</li>
```

versus

```html
<li>
  <div id="person-name">name 1</div>
  <div id="person-phone">123</div>
</li>
<li>
  <div id="person-name">name 1</div>
  <div id="person-phone">123</div>
</li>
```

2024-12-16 15:47 UTC, ericlinagora commented on tdrive/frontend/src/app/views/client/body/drive/browser.tsx
> +        <DocumentRow {...commonProps} testClassId="browser-document-row" />
because of the size of this PR, and the rapidly increasing risk of conflict, let's merge this for now

2024-12-16 15:48 UTC, ericlinagora approved these changes
Approval to figure this out without the pending huge PR merge since it's benign

2024-12-18 02:51 UTC, merged